#! /bin/sh -p
#PBS -l nodes=1:ppn=1
#PBS -N  AA_Resdeepgrowing_all_W2
#PBS -j oe

python3 /home/310122653/Git/DNN/wrapper_DNN.py $PBS_ARRAYID

#### qsub -t 39-206 Run_main2
### mystat
###  qdel 3326330[].osios
### https://confluence.atlas.philips.com/pages/viewpage.action?pageId=16491197 
### Info on qsub and qstat:
### http://docs.adaptivecomputing.com/torque/archive/3-0-2/2.1jobsubmission.php